# Generated by Django 4.2.6 on 2023-11-22 16:19

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=150)),
                ('slug_link', models.CharField(max_length=150, unique=True)),
                ('amount', models.IntegerField()),
                ('SAR_link', models.URLField(max_length=500)),
                ('AED_link', models.URLField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_phone_number', models.CharField(blank=True, max_length=31, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=31)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 16, 19, 3, 581915, tzinfo=datetime.timezone.utc))),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('wig_type', models.CharField(choices=[('اختر نوع الباروكة', 'اختر نوع الباروكة'), ('جذور امامية', 'جذور امامية'), ('جذور كامله', 'جذور كامله'), ('جذور دائرية 360', 'جذور دائرية 360')], max_length=150)),
                ('wig_long', models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('انش12', 'انش12'), ('انش14', 'انش14'), ('انش16', 'انش16'), ('انش18', 'انش18'), ('انش20', 'انش20'), ('انش22', 'انش22'), ('انش24', 'انش24'), ('انش26', 'انش26'), ('انش28', 'انش28'), ('انش30', 'انش30'), ('انش32', 'انش32'), ('انش34', 'انش34'), ('انش36', 'انش36'), ('انش38', 'انش38'), ('انش40', 'انش40')], max_length=150)),
                ('scalp_type', models.CharField(choices=[('اختر نوع الفروة', 'اختر نوع الفروة'), ('دانتيل', 'دانتيل'), ('حرير', 'حرير')], max_length=150)),
                ('wig_color', models.CharField(choices=[('اختر لون الباروكة', 'اختر لون الباروكة'), ('أسود طبيعى', 'أسود طبيعى'), ('بنى داكن', 'بنى داكن'), ('بنى فاتح', 'بنى فاتح'), ('اشقر', 'اشقر'), ('مخصل', 'مخصل')], max_length=150)),
                ('density', models.CharField(choices=[('اختر كثافة الباروكة', 'اختر كثافة الباروكة'), ('130', '130'), ('150', '150'), ('200', '200'), ('250', '250')], max_length=150)),
                ('price', models.IntegerField(default=1500)),
                ('pieces_num', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('باروكة شعر طبيعى', 'باروكة شعر طبيعى')], max_length=150)),
                ('wig_type', models.CharField(choices=[('اختر نوع الباروكة', 'اختر نوع الباروكة'), ('جذور امامية', 'جذور امامية'), ('جذور كامله', 'جذور كامله'), ('جذور دائرية 360', 'جذور دائرية 360')], max_length=150)),
                ('wig_long', models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('انش12', 'انش12'), ('انش14', 'انش14'), ('انش16', 'انش16'), ('انش18', 'انش18'), ('انش20', 'انش20'), ('انش22', 'انش22'), ('انش24', 'انش24'), ('انش26', 'انش26'), ('انش28', 'انش28'), ('انش30', 'انش30'), ('انش32', 'انش32'), ('انش34', 'انش34'), ('انش36', 'انش36'), ('انش38', 'انش38'), ('انش40', 'انش40')], max_length=150)),
                ('scalp_type', models.CharField(choices=[('اختر نوع الفروة', 'اختر نوع الفروة'), ('دانتيل', 'دانتيل'), ('حرير', 'حرير')], max_length=150)),
                ('wig_color', models.CharField(choices=[('اختر لون الباروكة', 'اختر لون الباروكة'), ('أسود طبيعى', 'أسود طبيعى'), ('بنى داكن', 'بنى داكن'), ('بنى فاتح', 'بنى فاتح'), ('اشقر', 'اشقر'), ('مخصل', 'مخصل')], max_length=150)),
                ('density', models.CharField(choices=[('اختر كثافة الباروكة', 'اختر كثافة الباروكة'), ('130', '130'), ('150', '150'), ('200', '200'), ('250', '250')], max_length=150)),
                ('price', models.IntegerField(default=1500, validators=[django.core.validators.MaxValueValidator(7000), django.core.validators.MinValueValidator(400)])),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discount_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('slug_link', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 16, 19, 3, 581915, tzinfo=datetime.timezone.utc))),
                ('done_ordered_time', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 16, 19, 3, 581915, tzinfo=datetime.timezone.utc))),
                ('ordered', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bill2')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon')),
                ('items', models.ManyToManyField(to='core.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_link', models.URLField(max_length=1000)),
                ('marketer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
