# Generated by Django 4.2.6 on 2023-11-22 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phones_alter_bill2_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(choices=[], default='3333333333333', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 16, 20, 49, 795662, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 16, 20, 49, 780043, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 16, 20, 49, 780043, tzinfo=datetime.timezone.utc)),
        ),
    ]
