# Generated by Django 4.2.6 on 2023-12-03 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_bill2_date_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='penality',
            name='days_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(0)]),
        ),
    ]
