# Generated by Django 4.2.6 on 2023-12-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='slug_link',
            field=models.SlugField(default='sdfsdf5bvsdf'),
            preserve_default=False,
        ),
    ]
