# Generated by Django 4.2.6 on 2023-12-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tasks_duration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='duration_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
    ]
