# Generated by Django 4.2.6 on 2023-12-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tasks_done_date_alter_tasks_duration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='duration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
