# Generated by Django 4.2.6 on 2023-12-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_tasks_done_date_alter_tasks_duration_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='duration_time',
        ),
    ]
