# Generated by Django 4.2.6 on 2023-12-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_tasks_duration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='done_task_is_read',
            field=models.BooleanField(default=False),
        ),
    ]
