# Generated by Django 4.2.6 on 2023-12-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tasks_done_task_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(choices=[], max_length=31),
        ),
    ]
