# Generated by Django 4.2.6 on 2023-12-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_phonenumber_phone_phonenumberr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberr',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.phones'),
        ),
    ]
