# Generated by Django 4.2.6 on 2023-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_phonenumberr_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(choices=[('1111111111111111', '1111111111111111'), ('222222222222', '222222222222'), ('3333333333333333', '3333333333333333'), ('4444444444444444', '4444444444444444'), ('55555555555555', '55555555555555')], max_length=31),
        ),
        migrations.DeleteModel(
            name='PhoneNumberr',
        ),
    ]
