# Generated by Django 4.2.6 on 2024-01-01 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phonenumberr'),
        ),
    ]
