# Generated by Django 4.2.6 on 2024-01-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_account_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phones',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-12 12:30:30'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
