# Generated by Django 4.2.6 on 2024-01-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_account_phone_number_phones_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phones',
            name='slug_link',
            field=models.SlugField(default='sdfsdfsdfsdf'),
            preserve_default=False,
        ),
    ]
