# Generated by Django 4.2.6 on 2024-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_phones_slug_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberr',
            name='date',
            field=models.DateTimeField(default='2023-11-12 18:20:20'),
            preserve_default=False,
        ),
    ]
