# Generated by Django 4.2.6 on 2024-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_phonenumberr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberr',
            name='slug_link',
            field=models.SlugField(default='SDFweweweeff'),
            preserve_default=False,
        ),
    ]
