# Generated by Django 4.2.6 on 2024-01-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_phonenumberr_slug_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_link',
            new_name='tiktok_account_link',
        ),
    ]
