# Generated by Django 4.2.6 on 2024-01-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug_link',
            field=models.SlugField(default='sdfsfdsdf'),
            preserve_default=False,
        ),
    ]
