# Generated by Django 4.2.6 on 2024-01-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_account_num_of_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='num_of_bills',
        ),
    ]
