# Generated by Django 4.2.6 on 2024-01-09 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_account_num_of_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill2',
            name='account',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='core.account'),
            preserve_default=False,
        ),
    ]
