# Generated by Django 4.2.6 on 2024-01-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_bank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='BankAccount',
        ),
    ]
