# Generated by Django 4.2.6 on 2024-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_delete_bank111'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlink',
            name='USD_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='addlink',
            name='AED_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='addlink',
            name='SAR_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='addlink',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addlink',
            name='link_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addlink',
            name='slug_link',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
