# Generated by Django 4.2.6 on 2024-01-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_addlink_usd_link_alter_addlink_aed_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phonenumber1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phones'),
        ),
    ]
