# Generated by Django 4.2.6 on 2024-01-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0050_account_phonenumber1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('tiktok_account_link', models.URLField(max_length=1000)),
                ('instagram_account_link', models.URLField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug_link', models.SlugField()),
                ('marketer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('phonenumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phonenumberr')),
                ('phonenumber1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phones')),
                ('seller_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
