# Generated by Django 4.2.6 on 2024-01-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0052_alter_acc_marketer_alter_acc_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='seller_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_seller_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
