# Generated by Django 4.2.6 on 2024-01-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_acc_seller_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acc',
        ),
    ]
