# Generated by Django 4.2.6 on 2024-01-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_rename_phonenumber1_account_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phonenumber',
        ),
    ]
