# Generated by Django 4.2.6 on 2024-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_account_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='IBAN',
            field=models.CharField(default='ggghh111 sssss 12', max_length=200),
            preserve_default=False,
        ),
    ]
