# Generated by Django 4.2.6 on 2024-01-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_bankaccount_swift_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='beneficiary_name',
            field=models.CharField(default='Ahmed El-Refaey', max_length=200),
            preserve_default=False,
        ),
    ]
