# Generated by Django 4.2.6 on 2024-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_bankaccount_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default='36252526252', max_length=200),
            preserve_default=False,
        ),
    ]
