# Generated by Django 4.2.6 on 2024-01-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_bankaccount_validation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill2',
            name='slug_code',
            field=models.SlugField(default='sdfsdf55sdddd'),
            preserve_default=False,
        ),
    ]
