# Generated by Django 4.2.6 on 2024-01-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_bill2_slug_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slug_code',
            field=models.SlugField(default='ddss112ss5s3s52s'),
            preserve_default=False,
        ),
    ]
