# Generated by Django 4.2.6 on 2024-01-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_orderitem_slug_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='slug_code',
        ),
    ]
