# Generated by Django 4.2.6 on 2024-01-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_remove_refund_slug_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='total_price',
            field=models.IntegerField(default=55000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refund',
            name='price',
            field=models.IntegerField(),
        ),
    ]
