# Generated by Django 4.2.6 on 2024-01-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_refund_total_price_alter_refund_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill2',
            name='payment_method',
            field=models.CharField(choices=[('اختر طريقة الدفع', 'اختر طريقة الدفع'), ('tabby', 'tabby'), ('tamara', 'tamara'), ('Stripe', 'Stripe'), ('PayTabs', 'PayTabs'), ('Apple Pay', 'Apple Pay'), ('Bank Account Pay', 'Bank Account Pay'), ('Upon receipt', 'Upon receipt')], default=2, max_length=150),
            preserve_default=False,
        ),
    ]
