# Generated by Django 4.2.6 on 2024-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_refund_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill2',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
