# Generated by Django 4.2.6 on 2024-01-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Offer',
            new_name='offer',
        ),
    ]
