# Generated by Django 4.2.6 on 2024-02-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_item_num_of_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill2',
            name='scalp_type',
            field=models.CharField(choices=[('اختر نوع الفروة', 'اختر نوع الفروة'), ('دانتيل سويسرى', 'دانتيل سويسرى'), ('حرير', 'حرير')], max_length=150),
        ),
        migrations.AlterField(
            model_name='bill2',
            name='wig_long',
            field=models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('انش10', 'انش10'), ('انش12', 'انش12'), ('انش14', 'انش14'), ('انش16', 'انش16'), ('انش18', 'انش18'), ('انش20', 'انش20'), ('انش22', 'انش22'), ('انش24', 'انش24'), ('انش26', 'انش26'), ('انش28', 'انش28'), ('انش30', 'انش30'), ('انش32', 'انش32'), ('انش34', 'انش34'), ('انش36', 'انش36'), ('انش38', 'انش38'), ('انش40', 'انش40')], max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='scalp_type',
            field=models.CharField(choices=[('اختر نوع الفروة', 'اختر نوع الفروة'), ('دانتيل سويسرى', 'دانتيل سويسرى'), ('حرير', 'حرير')], max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='wig_long',
            field=models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('انش10', 'انش10'), ('انش12', 'انش12'), ('انش14', 'انش14'), ('انش16', 'انش16'), ('انش18', 'انش18'), ('انش20', 'انش20'), ('انش22', 'انش22'), ('انش24', 'انش24'), ('انش26', 'انش26'), ('انش28', 'انش28'), ('انش30', 'انش30'), ('انش32', 'انش32'), ('انش34', 'انش34'), ('انش36', 'انش36'), ('انش38', 'انش38'), ('انش40', 'انش40')], max_length=150),
        ),
        migrations.AlterField(
            model_name='refund',
            name='scalp_type',
            field=models.CharField(choices=[('اختر نوع الفروة', 'اختر نوع الفروة'), ('دانتيل سويسرى', 'دانتيل سويسرى'), ('حرير', 'حرير')], max_length=150),
        ),
        migrations.AlterField(
            model_name='refund',
            name='wig_long',
            field=models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('انش10', 'انش10'), ('انش12', 'انش12'), ('انش14', 'انش14'), ('انش16', 'انش16'), ('انش18', 'انش18'), ('انش20', 'انش20'), ('انش22', 'انش22'), ('انش24', 'انش24'), ('انش26', 'انش26'), ('انش28', 'انش28'), ('انش30', 'انش30'), ('انش32', 'انش32'), ('انش34', 'انش34'), ('انش36', 'انش36'), ('انش38', 'انش38'), ('انش40', 'انش40')], max_length=150),
        ),
    ]
