# Generated by Django 4.2.6 on 2024-02-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_bill2_scalp_type_alter_bill2_wig_long_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBillsPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bill_pdf', models.FileField(upload_to='bills_pdf_documents/')),
                ('date', models.DateField()),
                ('slug_code', models.SlugField()),
            ],
        ),
    ]
