# Generated by Django 4.2.6 on 2024-02-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_allbillspdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill2',
            name='bill_pdf',
            field=models.FileField(default='billl_default_pdf.pdf', upload_to='bills_pdf_documents/'),
        ),
        migrations.AlterField(
            model_name='allbillspdf',
            name='bill_pdf',
            field=models.FileField(upload_to='monthly_bills_pdf/'),
        ),
    ]
