# Generated by Django 4.2.6 on 2024-02-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_bill2_bill_pdf_alter_allbillspdf_bill_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill2',
            name='wig_type',
            field=models.CharField(choices=[('اختر نوع الباروكة', 'اختر نوع الباروكة'), ('جذور امامية', 'جذور امامية'), ('جذور كامله', 'جذور كامله'), ('جذور دائرية 360', 'جذور دائرية 360'), ('لا شىء', 'لا شىء')], max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('باروكة شعر طبيعى', 'باروكة شعر طبيعى'), ('مقدمة باروكة شعر طبيعى', 'مقدمة باروكة شعر طبيعى')], max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='wig_type',
            field=models.CharField(choices=[('اختر نوع الباروكة', 'اختر نوع الباروكة'), ('جذور امامية', 'جذور امامية'), ('جذور كامله', 'جذور كامله'), ('جذور دائرية 360', 'جذور دائرية 360'), ('لا شىء', 'لا شىء')], max_length=150),
        ),
        migrations.AlterField(
            model_name='refund',
            name='wig_type',
            field=models.CharField(choices=[('اختر نوع الباروكة', 'اختر نوع الباروكة'), ('جذور امامية', 'جذور امامية'), ('جذور كامله', 'جذور كامله'), ('جذور دائرية 360', 'جذور دائرية 360'), ('لا شىء', 'لا شىء')], max_length=150),
        ),
    ]
