# Generated by Django 4.2.6 on 2024-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_bill2_wig_type_alter_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbillspdf',
            name='bill_pdf',
        ),
        migrations.AddField(
            model_name='allbillspdf',
            name='report_pdf',
            field=models.FileField(default='billl_default_pdf.pdf', upload_to='monthly_bills_pdf/'),
        ),
    ]
