# Generated by Django 4.2.6 on 2024-02-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_rename_report_pdf_allbillspdf_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbillspdf',
            name='pdf_file',
            field=models.FileField(default='billl_default_pdf.pdf', max_length=200, upload_to='monthly_bills_pdf/'),
        ),
    ]
