# Generated by Django 4.2.6 on 2024-01-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=models.CharField(choices=[('Choose Job Type', 'Choose Job Type'), ('Marketer', 'Marketer'), ('Seller', 'Seller')], default='Seller', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
